---
- name: Setup tools
  vars_prompt:
    - name: username
      prompt: "New username"
      private: no
    - name: password
      prompt: "New password"
      private: yes
      confirm: yes
      encrypt: 'sha512_crypt'
    - name: pubkey_path
      prompt: "SSH public key path"
      private: no
      default: ~/.ssh/id_rsa.pub
    - name: proxy_username
      prompt: "Proxy username"
      private: no
    - name: proxy_password
      prompt: "Proxy password"
      confirm: yes
      private: yes
    - name: proxy_ports
      prompt: "Proxy ports (comma separated)"
      default: 80,443,3128
  roles:
    - packages
    - user
    - ssh
    - proxy
  hosts: kogane
  become: yes
...
