- name: Authorize SSH public key
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ lookup('file', pubkey_path) }}"
- name: Copy SSH config file
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
- name: Disallow root login via password
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin.+$'
    replace: 'PermitRootLogin without-password'
    backup: yes
- name: Restart SSH server
  service:
    name: ssh
    state: reloaded